<template>
	<div class="grid justify-items-center gap-y-10 max-md:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
		<CProjectThumbnail
			:description="$t('projects[0].description')"
			picture-position="left"
			thumbnail="pigeactive_fr.png"
			:title="$t('projects[0].title')"
			url="https://pigeactive.fr"
		/>
		<CProjectThumbnail
			:description="$t('projects[1].description')"
			light
			picture-position="left"
			thumbnail="app_bedrock_im.png"
			:title="$t('projects[1].title')"
			url="https://app.bedrock.im"
		/>
		<CProjectThumbnail
			:description="$t('projects[2].description')"
			picture-position="left"
			thumbnail="dorianmoy_fr.png"
			:title="$t('projects[2].title')"
			url="https://dorianmoy.fr"
		/>
		<CProjectThumbnail
			:description="$t('projects[3].description')"
			light
			thumbnail="libertai_io.png"
			:title="$t('projects[3].title')"
			url="https://libertai.io"
		/>
		<CProjectThumbnail
			:description="$t('projects[4].description')"
			thumbnail="old_bedrock_im.png"
			:title="$t('projects[4].title')"
			url="https://old.bedrock.im"
		/>
		<CProjectThumbnail
			:description="$t('projects[5].description')"
			light
			picture-position="left"
			thumbnail="area_github.png"
			:title="$t('projects[5].title')"
			url="https://github.com/RezaRahemtola/Area"
		/>
		<CProjectThumbnail
			:description="$t('projects[6].description')"
			light
			picture-position="left"
			thumbnail="trombiday_github.png"
			:title="$t('projects[6].title')"
			url="https://github.com/RezaRahemtola/Survivor"
		/>
	</div>
</template>
<script lang="ts" setup>
import CProjectThumbnail from "../components/CProjectThumbnail.vue";
</script>
<style></style>
